name: summarizor
description: "A Flutter App to Summarize and Teach using AI."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: poppinsreg
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf