name: summarizor
description: "A Flutter App to Summarize and Teach using AI."
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.0

  provider: ^6.1.2

  firebase_core: ^3.8.0
  firebase_auth: ^5.5.2
  smooth_page_indicator: ^1.2.1
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  file_picker: ^10.1.9
  syncfusion_flutter_pdf: ^24.1.41
  path_provider: ^2.1.1
  http: ^1.2.0
  pdfx: ^2.9.1
  dotted_border: ^2.0.0
  cupertino_icons: ^1.0.8
  archive: ^3.4.6
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: poppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: poppinsreg
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf